### ISSUE TITLE
Set up a SQL Server sandbox

### ISSUE THREAD

**Issue by aslilac** [xaslilac/sandbox#23]
Apparently it runs on Linux and is containerize these days? Tried to run it but it didn't work, though I only tried on ARM machines which I doubt helps

```yml
version: "3"
services:
  server:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest

    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ":oAAA95B"
```
